name: Core
version: ${project.version}
main: io.nebulamc.core.Core
api-version: 1.17
authors: [ 0xBit ]
description: The Main Core Plugin for Nebula Towny
website: https://nebulamc.io/plugins/core
depend:
  - Towny
permissions:
  nebula.core.rtp:
    description: Allows you to use /rtp
    default: op
commands:
  rtp:
    description: Teleports you to a random location.
    permission: nebula.command.rtp
    permission-message: You do not have permission to run this command!
    usage: /rtp <player> <x> <z>
  mapcolor:
    description: Allows VIP+ to set their nations map color on the Dynmap!
    permission: nebula.command.mapcolor
    permission-message: You do not have permission to run this command!
    usage: /mapcolor <color>
  core:
    description: Informational Panel about Nebula Towny Core.
    permission: nebula.command.core
    permission-message: You do not have permission to run this command!
    usage: /core <args>